# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-slim

WORKDIR /app

# Install TypeScript globally
RUN npm install -g typescript

# Copy package files
COPY package*.json ./

# Install dependencies (skip prepare script)
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build TypeScript
RUN npm run build

# Clean up dev dependencies
RUN npm prune --production

# Run the server
CMD ["node", "dist/index.js"]
